#ifndef LATEX_CORE_HPP
#define LATEX_CORE_HPP

#include <string>
#include <vector>

#include "../sem_analyzer/semantic_analyzer.hpp"
#include "../lexer/lexer.hpp"
#include "../parser/parser.hpp"

class LatexCore
{
public:
    // ======================
    // -- PUBLIC DATA
    // ======================

    std::string input_text;

    std::vector<Token> tokens;
    std::vector<SemanticError> errors;

    Lexer lexer;
    Parser parser;
    SemanticAnalyzer analyzer;

    // ======================
    // -- CONSTRUCTOR
    // ======================

    /// @brief Constructor for Latex Core
    /// @param text The text to process
    LatexCore(std::string text) : input_text(std::move(text)), lexer(input_text)
    {
        tokens = lexer.tokenize();

        Parser parser_exec(tokens);
        auto ast = parser_exec.parse();

        analyzer.analyze(ast);
        errors = analyzer.get_errors();
    }

    // ======================
    // -- PUBLIC METHODS
    // ======================

    /// @brief Print the tokens generated by the lexer
    /// @note [DEBUG]
    void print_tokens();

    /// @brief Print the errors found during semantic analysis
    /// @note [DEBUG]
    void print_analysis();

    /// @brief Return analysis results
    /// @return std::vector<SemanticError>
    std::vector<SemanticError> return_errors();
};

#endif
